spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:dev_db"
    username: "sa"
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization : true
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect